export const MODES=['showdown','gems','control','ball'];
export const BASE=[['lex','Hamza. S.',4800,1100,'Lernboost'],['lina','LINA',4200,1200,'Soundwelle'],['profz','PROF. Z',5200,1000,'Zahlenblitz'],['emre','EMRE',4700,1050,'Wissensschild'],['nela','NELA',5400,950,'Sprint'],['yusuf','YUSUF',4500,1150,'Turbo'],['sara','SARA',4600,1100,'Teamboost'],['kian','KIAN',4400,1250,'Schallimpuls'],['arda','ARDA',4000,1300,'Schattenlauf']].map(([id,name,hp,damage,skill],i)=>({id,name,hp,damage,skill,range:420,reload:1.2,speed:195,superDamage:damage*2,rarity:i===0?'STARTER':i%3?'EPISCH':'SELTEN',cost:i===0?0:300,published:true,image:'',sprite:i}));
export const clamp=(n,min,max)=>Math.min(max,Math.max(min,Number.isFinite(Number(n))?Number(n):min));
export function fresh(name){return {name,wallet:{coins:0,gems:0,stars:0,power:0,owned:[]},fighters:{selected:'lex',levels:{},trophies:{}},collection:{version:3,brawlers:['lex'],ldrop:0,mega:0},views:{color:'#ffffff',skin:0,skinOwned:[],credits:0,dailyDate:'',dailyCount:0,chat:[]},stats:{matches:0,wins:0,kills:0,questClaims:[],passClaims:[]}}}
export function normalize(p,name){const f=fresh(name);p=p&&typeof p==='object'?p:{};for(const key of ['wallet','fighters','collection','views','stats'])f[key]={...f[key],...p[key]};f.name=String(p.name||name).slice(0,18);for(const k of ['coins','gems','stars','power'])f.wallet[k]=clamp(f.wallet[k],0,1e9);f.views.credits=clamp(f.views.credits,0,1e9);f.collection.brawlers=Array.from(new Set(['lex',...(Array.isArray(f.collection.brawlers)?f.collection.brawlers:[])]));f.collection.ldrop=clamp(f.collection.ldrop,0,10000);f.collection.mega=clamp(f.collection.mega,0,10000);f.fighters.trophies=f.fighters.trophies||{};f.fighters.levels=f.fighters.levels||{};f.stats.questClaims=Array.isArray(f.stats.questClaims)?f.stats.questClaims:[];f.stats.passClaims=Array.isArray(f.stats.passClaims)?f.stats.passClaims:[];return f}
export function wallsFor(mode){const w=[];for(const y of [240,500,870,1170])for(const x of [95,550])w.push({x,y,w:115,h:70});w.push({x:300,y:405,w:160,h:70},{x:300,y:1000,w:160,h:70});if(mode==='showdown')w.push({x:335,y:680,w:90,h:90});return w}
const hitWall=(s,x,y,r=20)=>x<r||x>760-r||y<40||y>1410||s.walls.some(w=>x>w.x-r&&x<w.x+w.w+r&&y>w.y-r&&y<w.y+w.h+r);
function move(s,a,dx,dy){if(!hitWall(s,a.x+dx,a.y))a.x+=dx;if(!hitWall(s,a.x,a.y+dy))a.y+=dy}
export function actor(username,fighter,team,slot,bot=false){const x=[170,380,590][slot%3],y=team?140:1310;return {username,id:fighter.id,name:fighter.name,team,bot,x,y,hp:fighter.hp,maxHp:fighter.hp,damage:fighter.damage,range:fighter.range,speed:fighter.speed,reload:fighter.reload,superDamage:fighter.superDamage,projectiles:fighter.projectiles||1,superProjectiles:fighter.superProjectiles||3,projectileColor:fighter.projectileColor||'#65ddff',ammo:3,reloadClock:0,cool:0,charge:0,respawn:0,dead:false,gems:0,kills:0,input:{dx:0,dy:0,angle:-Math.PI/2,fire:false,super:false},lastSeq:-1,lastSeen:0,disconnected:false}}
export function beginRoom(room,catalog,now){const botsNeeded=6-room.players.length;for(let i=0;i<botsNeeded;i++)room.players.push({username:'bot_'+i,id:BASE[(i+1)%BASE.length].id,team:room.players.length%2,bot:true});room.phase='playing';room.startedAt=now;room.lastTick=now;room.time=room.map?.duration||120;room.score=[0,0];room.walls=room.map?room.map.cells.filter(c=>c.type==='wall').map(c=>({x:c.x,y:c.y,w:40,h:40})):wallsFor(room.mode);room.bushes=room.map?.cells.filter(c=>c.type==='bush')||[];room.hazards=room.map?.cells.filter(c=>c.type==='lava')||[];room.actors=room.players.map((p,i)=>{const f=catalog.find(f=>f.id===p.id)||BASE[0],boost=1+.05*((p.level||1)-1);return {...actor(p.username,{...f,hp:Math.round(f.hp*boost),damage:Math.round(f.damage*boost),superDamage:Math.round(f.superDamage*boost)},p.team,i,p.bot),skinId:p.skinId||0}});room.bullets=[];room.pickups=[];room.gemClock=1;room.ball={x:380,y:725,vx:0,vy:0,owner:null};room.version=0;room.result=null}
function shoot(s,a,superShot){if(a.cool>0||a.dead)return;if(s.mode==='ball'&&s.ball.owner===a.username){s.ball.owner=null;s.ball.vx=Math.cos(a.input.angle)*600;s.ball.vy=Math.sin(a.input.angle)*600;a.cool=.4;return}if(superShot&&a.charge<100)return;if(!superShot&&a.ammo<1)return;const angle=Number.isFinite(a.input.angle)?a.input.angle:-Math.PI/2;if(superShot)a.charge=0;else a.ammo--;a.cool=.28;const count=superShot?a.superProjectiles:a.projectiles;const angles=Array.from({length:count||1},(_,i)=>angle+(i-((count||1)-1)/2)*.14);for(const angle of angles)s.bullets.push({owner:a.username,team:a.team,x:a.x,y:a.y,vx:Math.cos(angle)*650,vy:Math.sin(angle)*650,life:a.range/650,damage:superShot?a.superDamage:a.damage,super:superShot,color:a.projectileColor})}
function kill(s,a,source){a.hp=0;a.dead=true;a.respawn=s.mode==='showdown'?999:4;if(s.ball.owner===a.username)s.ball.owner=null;for(let i=0;i<a.gems;i++)s.pickups.push({x:a.x+(i%3)*12-12,y:a.y+Math.floor(i/3)*12});a.gems=0;if(source)source.kills++}
function finish(s,winner,reason){s.phase='finished';s.result={winner,reason,at:s.lastTick};s.bullets=[]}
function step(s,dt){s.time-=dt;s.gemClock-=dt;
 for(const a of s.actors){if(a.dead){a.respawn-=dt;if(a.respawn<=0){a.dead=false;a.hp=a.maxHp;a.x=[170,380,590][s.actors.indexOf(a)%3];a.y=a.team?130:1320;a.ammo=3}continue}a.cool=Math.max(0,a.cool-dt);a.reloadClock+=dt;if(a.ammo<3&&a.reloadClock>=a.reload){a.ammo++;a.reloadClock=0}let inp=a.input;if(a.bot){const target=s.actors.filter(b=>!b.dead&&b.username!==a.username&&(s.mode==='showdown'||b.team!==a.team)).sort((b,c)=>Math.hypot(a.x-b.x,a.y-b.y)-Math.hypot(a.x-c.x,a.y-c.y))[0];let tx=target?.x||380,ty=target?.y||725;if(s.mode==='gems'&&s.pickups.length){tx=s.pickups[0].x;ty=s.pickups[0].y}if(s.mode==='control'){tx=380;ty=725}if(s.mode==='ball'){tx=s.ball.owner===a.username?380:s.ball.x;ty=s.ball.owner===a.username?(a.team?1380:70):s.ball.y}const d=Math.hypot(tx-a.x,ty-a.y)||1;inp={dx:d>140?(tx-a.x)/d:0,dy:d>140?(ty-a.y)/d:0,angle:target?Math.atan2(target.y-a.y,target.x-a.x):-Math.PI/2,fire:!!target&&Math.hypot(target.x-a.x,target.y-a.y)<a.range,super:a.charge>=100};a.input=inp}else if(s.lastTick-a.lastSeen>1500){inp={dx:0,dy:0,angle:0,fire:false};a.disconnected=true}else a.disconnected=false;let len=Math.max(1,Math.hypot(inp.dx,inp.dy));if(a.bot&&hitWall(s,a.x+inp.dx*40,a.y+inp.dy*40)){const candidates=[[1,0],[-1,0],[0,1],[0,-1]].filter(([dx,dy])=>!hitWall(s,a.x+dx*45,a.y+dy*45));const direction=candidates.sort((b,c)=>Math.hypot(a.x+b[0]*90-380,a.y+b[1]*90-725)-Math.hypot(a.x+c[0]*90-380,a.y+c[1]*90-725))[0];if(direction){inp={...inp,dx:direction[0],dy:direction[1]};len=1}}move(s,a,clamp(inp.dx,-1,1)/len*a.speed*dt,clamp(inp.dy,-1,1)/len*a.speed*dt);if(inp.super)shoot(s,a,true);else if(inp.fire)shoot(s,a,false);
 if(s.mode==='showdown'&&s.time<75){const inset=(75-s.time)*4;if(a.x<inset||a.x>760-inset||a.y<inset||a.y>1450-inset){a.hp-=dt*350;if(a.hp<=0)kill(s,a,null)}}
 if(!a.dead&&s.hazards?.some(c=>a.x>=c.x&&a.x<c.x+40&&a.y>=c.y&&a.y<c.y+40)){a.hp-=dt*(s.map?.hazardDamage||200);if(a.hp<=0)kill(s,a,null)}
 }
 for(const b of s.bullets){b.life-=dt;b.x+=b.vx*dt;b.y+=b.vy*dt;if(hitWall(s,b.x,b.y,0))b.life=0;if(b.life<=0)continue;for(const a of s.actors){if(a.dead||a.username===b.owner||(s.mode!=='showdown'&&a.team===b.team))continue;if(Math.hypot(b.x-a.x,b.y-a.y)<25){a.hp-=b.damage;b.life=0;const owner=s.actors.find(a=>a.username===b.owner);if(owner)owner.charge=Math.min(100,owner.charge+25);if(a.hp<=0)kill(s,a,owner);break}}}s.bullets=s.bullets.filter(b=>b.life>0);
 if(s.mode==='showdown'){const living=s.actors.filter(a=>!a.dead);if(living.length<=1)finish(s,living[0]?.username||null,'Letzter Brawler')}
 if(s.mode==='gems'){if(s.gemClock<=0&&s.pickups.length<20){s.gemClock=2;s.pickups.push({x:350+(s.version%5)*14,y:680+(s.version%7)*15})}s.pickups=s.pickups.filter(g=>{const a=s.actors.find(a=>!a.dead&&Math.hypot(a.x-g.x,a.y-g.y)<30);if(a){a.gems++;return false}return true});s.score=[0,1].map(t=>s.actors.filter(a=>a.team===t).reduce((n,a)=>n+a.gems,0));if(Math.max(...s.score)>=10){if(s.gemLeader===s.score.indexOf(Math.max(...s.score)))s.gemHold=(s.gemHold||0)+dt;else{s.gemLeader=s.score.indexOf(Math.max(...s.score));s.gemHold=0}if(s.gemHold>=10)finish(s,s.gemLeader,'10 Juwelen gehalten')}else{s.gemHold=0;s.gemLeader=null}}
 if(s.mode==='control'){const teams=new Set(s.actors.filter(a=>!a.dead&&Math.hypot(a.x-380,a.y-725)<140).map(a=>a.team));if(teams.size===1)s.score[[...teams][0]]+=dt*5;if(Math.max(...s.score)>=100)finish(s,s.score[0]>s.score[1]?0:1,'Zone erobert')}
 if(s.mode==='ball'){const b=s.ball,owner=s.actors.find(a=>a.username===b.owner&&!a.dead);if(owner){b.x=owner.x;b.y=owner.y; }else{b.owner=null;const px=b.x,py=b.y;b.x+=b.vx*dt;b.y+=b.vy*dt;b.vx*=.985;b.vy*=.985;if(b.x<20||b.x>740){b.x=clamp(b.x,20,740);b.vx*=-.8}if(s.walls.some(w=>b.x>w.x&&b.x<w.x+w.w&&b.y>w.y&&b.y<w.y+w.h)){b.x=px;b.y=py;b.vx*=-.7;b.vy*=-.7}if(Math.hypot(b.vx,b.vy)<180){const a=s.actors.find(a=>!a.dead&&Math.hypot(a.x-b.x,a.y-b.y)<35);if(a)b.owner=a.username}}if((b.y<55||b.y>1395)&&b.x>245&&b.x<515){s.score[b.y<55?0:1]++;b.x=380;b.y=725;b.vx=b.vy=0;b.owner=null;for(const a of s.actors){a.x=[170,380,590][s.actors.indexOf(a)%3];a.y=a.team?130:1320}if(Math.max(...s.score)>=3)finish(s,s.score[0]>s.score[1]?0:1,'Drei Tore')}else if(b.y<40||b.y>1410){b.y=clamp(b.y,40,1410);b.vy*=-.8}for(const a of s.actors)if(a.bot&&b.owner===a.username){a.input.angle=a.team?Math.PI/2:-Math.PI/2;if((a.team?a.y>1100:a.y<350))shoot(s,a,false)}}
 if(s.time<=0&&s.phase==='playing'){if(s.mode==='showdown'){const alive=s.actors.filter(a=>!a.dead).sort((a,b)=>b.hp-a.hp);finish(s,alive[0]?.username||null,'Zeit abgelaufen')}else finish(s,s.score[0]===s.score[1]?null:s.score[0]>s.score[1]?0:1,'Zeit abgelaufen')}
}
export function tick(room,now){if(room.phase!=='playing')return;let remaining=Math.min(3,Math.max(0,(now-room.lastTick)/1000));room.lastTick=now;while(remaining>0&&room.phase==='playing'){const dt=Math.min(.04,remaining);step(room,dt);remaining-=dt}room.version++}
export function applyInput(room,username,input,now){const a=room.actors?.find(a=>a.username===username&&!a.bot);if(!a)return;const seq=Math.floor(clamp(input.seq,0,1e12));if(seq<=a.lastSeq)return;a.lastSeq=seq;a.lastSeen=now;a.input={dx:clamp(input.dx,-1,1),dy:clamp(input.dy,-1,1),angle:clamp(input.angle,-Math.PI,Math.PI),fire:input.fire===true,super:input.super===true}}
