import {askAI} from './ai-provider.js';
import {clamp} from './stars-game.js';
import {safeMapCell} from './stars-maps.js';
const fail=(status,message)=>{const e=Error(message);e.status=status;throw e};
const color=(x,f)=>/^#[a-f\d]{6}$/i.test(x)?x:f;
export async function generateStarsDraft(body){
 const kind=body.kind;if(!['brawler','map','skin'].includes(kind))fail(400,'Unbekannter Entwurfstyp');const prompt=String(body.prompt||'').trim();if(prompt.length<5||prompt.length>4000)fail(400,'Beschreibe deinen Entwurf mit 5 bis 4000 Zeichen.');
 const shapes={brawler:'{"name":"Name","hp":4800,"damage":1100,"range":420,"speed":195,"reload":1.2,"superDamage":2200,"projectiles":1,"superProjectiles":3,"projectileColor":"#65ddff","cost":300,"skill":"Super-Name","superType":"burst","superColor":"#ffdf66","projectileSize":6,"projectileSpeed":650,"superSpread":0.14,"rarity":"EPISCH","design":{"outfit":"#2177dc","hair":"#593829","skin":"#e6a46a","hat":"none"}}',skin:'{"name":"Skin-Name","design":{"outfit":"#2177dc","hair":"#593829","skin":"#e6a46a","hat":"cap"}}',map:'{"name":"Spielfeld","theme":"school","duration":120,"hazardDamage":200,"cells":[{"x":80,"y":240,"type":"wall"}]}'};
 const answer=await askAI({instructions:'Du entwirfst spielbare Inhalte für Lessing Stars. Antworte ausschließlich mit einem JSON-Objekt im vorgegebenen Format. Kein Code, HTML oder SVG. superType burst (Projektilsalve), heal (Heilung), dash (Sprint); superColor Hexfarbe, projectileSize 3..20, projectileSpeed 200..1000, superSpread 0..1.2. Brawler: hp 200..20000, damage 50..5000, range 100..800, speed 100..300, reload 0.4..3, superDamage 100..10000, projectiles 1..5, superProjectiles 1..7, cost 0..4000. rarity: SELTEN, SUPERSELTEN, EPISCH, MYTHISCH, LEGENDÄR. design: sechsstellige Hexfarben, hat none/cap/crown/mask. Karten 760x1450: Raster 40px, x 0..720, y 240..1160. Zentrale Zone x=200..520,y=600..800 freilassen. Maximal 150 Zellen, keine Duplikate; wall blockiert, bush dekoriert, lava schadet. Freie Wege zwischen Nord und Süd. theme school/forest/night. duration 30..300, hazardDamage 50..1000. Schema: '+shapes[kind],input:[{role:'user',content:prompt}],maxTokens:5000});
 let draft;try{draft=JSON.parse(answer.replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,''))}catch{fail(502,'Die KI hat keinen gültigen Entwurf geliefert. Bitte erneut versuchen.')}if(!draft||typeof draft!=='object'||Array.isArray(draft))fail(502,'Ungültiger KI-Entwurf');const name=String(draft.name||'').trim().slice(0,kind==='map'?30:24);if(!name)fail(502,'Dem KI-Entwurf fehlt ein Name.');
 const d=draft.design||{},design={outfit:color(d.outfit,'#2177dc'),hair:color(d.hair,'#593829'),skin:color(d.skin,'#e6a46a'),hat:['none','cap','crown','mask'].includes(d.hat)?d.hat:'none'};
 if(kind==='skin')return {kind,draft:{name,design}};
 if(kind==='brawler'){const clean={name,design,published:false,rarity:['SELTEN','SUPERSELTEN','EPISCH','MYTHISCH','LEGENDÄR'].includes(draft.rarity)?draft.rarity:'EPISCH',skill:String(draft.skill||'Super-Angriff').slice(0,40),projectileColor:color(draft.projectileColor,'#65ddff'),superType:['burst','heal','dash'].includes(draft.superType)?draft.superType:'burst',superColor:color(draft.superColor,'#ffdf66'),projectileSize:clamp(draft.projectileSize||6,3,20),projectileSpeed:clamp(draft.projectileSpeed||650,200,1000),superSpread:clamp(draft.superSpread??.14,0,1.2)};for(const [key,min,max,fallback] of [['hp',200,20000,4800],['damage',50,5000,1100],['range',100,800,420],['speed',100,300,195],['reload',.4,3,1.2],['superDamage',100,10000,2200],['projectiles',1,5,1],['superProjectiles',1,7,3],['cost',0,4000,300]])clean[key]=clamp(draft[key]??fallback,min,max);clean.projectiles=Math.round(clean.projectiles);clean.superProjectiles=Math.round(clean.superProjectiles);return {kind,draft:clean}}
 if(!Array.isArray(draft.cells))fail(502,'Der Kartenentwurf enthält keine Felder.');const used=new Set(),cells=[];for(const c of draft.cells.slice(0,300)){if(!c||typeof c!=='object')continue;const {x,y,type}=c,key=x+':'+y;if(Number.isInteger(x)&&Number.isInteger(y)&&x%40===0&&y%40===0&&x>=0&&x<=720&&y<=1400&&safeMapCell(x,y)&&['wall','bush','lava'].includes(type)&&!used.has(key)){used.add(key);cells.push({x,y,type})}}if(!cells.length)fail(502,'Die KI hat keine gültigen Kartenfelder geliefert. Bitte erneut versuchen.');return {kind,draft:{name,cells,theme:['school','forest','night'].includes(draft.theme)?draft.theme:'school',duration:Math.round(clamp(draft.duration||120,30,300)),hazardDamage:Math.round(clamp(draft.hazardDamage||200,50,1000)),published:false}};
}
