// Studio 03: responsive lobby, fighter designer, shared maps and four-tap drops.
const nativeHome=$('.mobile-home');
const hero=document.createElement('div');hero.className='studio-hero';hero.append($('#mobileFighter'),$('#mobileSelected'));
const menu=document.createElement('div');menu.className='studio-menu';menu.append($('.mobile-actions'),$('#mobilePlay'));
const homeBody=document.createElement('div');homeBody.className='studio-home-body';homeBody.append(hero,menu);nativeHome.append(homeBody);
for(const old of [collectionBadge,trophyDisplay,levelDisplay])old.classList.add('obsolete-lobby-label');
versionBadge.textContent='STUDIO 03 · 01.10.2026';
extraLogin=function(){returnLobby();authMode(false);extra('login');$('#loginUser').value='';$('#loginUser').focus()};
const studioAuthMode=authMode;authMode=function(mode){studioAuthMode(mode);$('#authCaption').textContent=mode?'Erstelle freiwillig ein Konto. Hamza. S. ist dein Start-Brawler.':'Du kannst ohne Anmeldung spielen. Mit Konto spielst du auf anderen Geräten weiter.'};
const studioAccount=()=>registeredPlayer()?openAccountSettings():extraLogin();$('#mobileAccount').onclick=studioAccount;$('#navAccount').onclick=studioAccount;
const studioCatalog=loadCatalog;loadCatalog=async function(){await studioCatalog();for(const f of fighters)if(f.id==='lex'&&['LEX','Hamza.S.'].includes(f.name))f.name='Hamza. S.';renderLobbyFighter()};
for(const f of fighters)if(f.id==='lex')f.name='Hamza. S.';
renderMobileHome();

// The same saved values are used by the authoritative combat simulation.
const projectileFields=document.createElement('div');projectileFields.className='fields';projectileFields.innerHTML='<label>Projektile pro Angriff<input name="projectiles" type="number" min="1" max="5" value="1" required></label><label>Projektile pro Super<input name="superProjectiles" type="number" min="1" max="7" value="3" required></label><label>Projektilfarbe<input name="projectileColor" type="color" value="#65ddff"></label>';
$('#editorForm').querySelector('button[type="submit"]').before(projectileFields);
$('#editorForm .muted').textContent='Projektile, Schaden und Farbe werden im Kampf verwendet. Eigene Figurenbilder erscheinen in Lobby und Match.';
const design=document.createElement('section');design.className='fighter-designer';design.innerHTML='<h2>Figur selbst designen</h2><div class="designer-layout"><canvas id="designCanvas" width="320" height="400" aria-label="Figurenvorschau"></canvas><div><label>Outfit-Farbe<input id="designOutfit" type="color" value="#2177dc"></label><label>Haarfarbe<input id="designHair" type="color" value="#593829"></label><label>Hautfarbe<input id="designSkin" type="color" value="#e6a46a"></label><label>Accessoire<select id="designHat"><option value="none">Ohne</option><option value="cap">Kappe</option><option value="crown">Krone</option><option value="mask">Maske</option></select></label><button type="button" id="designApply">DESIGN ÜBERNEHMEN</button><p class="muted">Danach „Brawler speichern“. Alternativ kannst du ein eigenes Bild hochladen.</p></div></div>';
$('#editorForm').prepend(design);
function drawDesign(){const c=$('#designCanvas'),g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);const outfit=$('#designOutfit').value,hair=$('#designHair').value,skin=$('#designSkin').value,hat=$('#designHat').value;const oval=(x,y,rx,ry,color)=>{g.fillStyle=color;g.beginPath();g.ellipse(x,y,rx,ry,0,0,Math.PI*2);g.fill();g.strokeStyle='#102446';g.lineWidth=5;g.stroke()};oval(160,375,85,12,'#14395755');oval(124,308,25,51,'#123a75');oval(195,308,25,51,'#123a75');oval(120,358,34,19,'#dcefff');oval(201,358,34,19,'#dcefff');oval(94,229,24,47,skin);oval(226,229,24,47,skin);oval(160,229,65,76,outfit);oval(160,123,67,73,skin);oval(151,73,65,32,hair);oval(102,96,16,34,hair);oval(211,92,18,34,hair);oval(135,123,9,13,'#152640');oval(185,123,9,13,'#152640');g.strokeStyle='#743426';g.lineWidth=5;g.beginPath();g.arc(160,149,21,.2,Math.PI-.2);g.stroke();g.font='900 50px system-ui';g.textAlign='center';g.fillStyle='#ffe16c';g.fillText('L',160,250);if(hat==='cap'){oval(159,67,72,22,outfit);g.fillRect(152,64,99,18)}if(hat==='crown'){g.fillStyle='#ffe16c';g.beginPath();g.moveTo(98,72);g.lineTo(93,24);g.lineTo(125,45);g.lineTo(157,13);g.lineTo(189,45);g.lineTo(219,24);g.lineTo(216,72);g.closePath();g.fill();g.stroke()}if(hat==='mask'){g.fillStyle='#20304f';g.fillRect(113,105,95,29);g.fillStyle='#fff';g.fillRect(126,111,20,13);g.fillRect(174,111,20,13)}}
for(const id of ['designOutfit','designHair','designSkin','designHat'])$('#'+id).oninput=drawDesign;
$('#designApply').onclick=()=>{editorImage=$('#designCanvas').toDataURL('image/png');const image=new Image();image.src=editorImage;image.alt='Dein Brawler-Design';$('#editorPreview').replaceChildren(image);$('#editorStatus').textContent='Design übernommen. Jetzt Brawler speichern.'};
const studioEditorSelect=editorSelect;editorSelect=function(f){studioEditorSelect(f);for(const [key,fallback] of [['projectiles',1],['superProjectiles',3],['projectileColor','#65ddff']])$('#editorForm').elements[key].value=f?.[key]??fallback;$('#editorUpload').value='';drawDesign()};
drawDesign();

// Editable tile maps. Protected spawn/objective areas keep all four modes playable.
let mapCatalog=[],mapDraft={id:null,name:'Mein Spielfeld',cells:[],theme:'school',duration:120,hazardDamage:200,published:true},mapPainting=false;
const mapScreen=document.createElement('section');mapScreen.id='mapStudio';mapScreen.className='release-screen hidden';mapScreen.innerHTML='<header><button id="mapBack">← Lobby</button><h1>SPIELFELD-WERKSTATT</h1><button id="mapNew">+ NEUES FELD</button></header><div class="release-layout"><section class="release-card"><form id="mapForm"><label>Name<input name="name" maxlength="30" value="Mein Spielfeld" required></label><div class="fields"><label>Design<select name="theme"><option value="school">Schulhof</option><option value="forest">Wald</option><option value="night">Nacht</option></select></label><label>Matchdauer (Sek.)<input name="duration" type="number" min="30" max="300" value="120" required></label><label>Lava-Schaden / Sek.<input name="hazardDamage" type="number" min="50" max="1000" value="200" required></label><label>Werkzeug<select id="mapBrush"><option value="wall">Wand</option><option value="bush">Busch (Dekoration)</option><option value="lava">Lava (Schaden)</option><option value="erase">Radierer</option></select></label></div><label class="check"><input name="published" type="checkbox" checked> Für Spieler freigeben</label><button type="submit">SPIELFELD SPEICHERN</button><p id="mapStatus" role="status"></p></form><p>Wände blockieren Bewegung und Schüsse. Lava verursacht Schaden beim Betreten. Büsche sind Dekoration. Blaue Startflächen und die Zielzone bleiben frei.</p><h2>Gespeicherte Spielfelder</h2><div id="mapList"></div><button id="mapTest">GESPEICHERTES FELD TESTEN</button></section><section class="release-card"><h2>Tippen oder ziehen zum Zeichnen</h2><p class="muted">Maximal 300 Felder. Die Vorschau ist scrollbar, damit du auf dem Handy genau zeichnen kannst.</p><div class="map-canvas-scroll"><canvas id="mapCanvas" width="760" height="1450" aria-label="Spielfeld bearbeiten"></canvas></div></section></div>';
document.querySelector('main.lobby').append(mapScreen);
const mapButton=document.createElement('button');mapButton.textContent='SPIELFELDER ERSTELLEN / ÄNDERN';mapButton.onclick=()=>openMapStudio();$('#adminScreen .admin-layout section').append(mapButton);
const editorMapButton=document.createElement('button');editorMapButton.textContent='SPIELFELDER';editorMapButton.onclick=()=>openMapStudio();editorScreen.querySelector('header').append(editorMapButton);
function mapCellSafe(x,y){return y>=220&&y<=1190&&!(x<540&&x+40>220&&y<830&&y+40>610)}
function drawMap(){const c=$('#mapCanvas'),g=c.getContext('2d'),theme=$('#mapForm').elements.theme.value;g.fillStyle=theme==='forest'?'#214c35':theme==='night'?'#162846':'#35556a';g.fillRect(0,0,760,1450);for(let y=0;y<1440;y+=40)for(let x=0;x<760;x+=40){if(!mapCellSafe(x,y)){g.fillStyle='#49adf033';g.fillRect(x,y,40,40)}g.strokeStyle='#a9d9ee33';g.strokeRect(x,y,40,40)}for(const cell of mapDraft.cells){g.fillStyle={wall:'#be8c54',bush:'#49ae61',lava:'#ff7047'}[cell.type];g.fillRect(cell.x+2,cell.y+2,36,36)}g.fillStyle='#d7eeff';g.font='bold 28px system-ui';g.textAlign='center';g.fillText('START',380,145);g.fillText('ZIELZONE',380,730);g.fillText('START',380,1330)}
function selectMap(map){mapDraft=map?JSON.parse(JSON.stringify(map)):{id:null,name:'Mein Spielfeld',cells:[],theme:'school',duration:120,hazardDamage:200,published:true};const form=$('#mapForm');for(const k of ['name','theme','duration','hazardDamage'])form.elements[k].value=mapDraft[k];form.elements.published.checked=mapDraft.published;$('#mapStatus').textContent='';drawMap()}
async function loadMapCatalog(){const data=await starsRequest('maps');mapCatalog=data.maps;return data.maps}
function renderMapList(){$('#mapList').replaceChildren();for(const map of mapCatalog){const row=document.createElement('div');row.className='release-row';const name=document.createElement('strong');name.textContent=map.name+' · '+(map.published?'Freigegeben':'Entwurf');const button=document.createElement('button');button.textContent='BEARBEITEN';button.onclick=()=>selectMap(map);row.append(name,button);$('#mapList').append(row)}}
async function openMapStudio(){if(!releaseAdmin()){toast('Nur Admin');return}returnLobby();mapScreen.classList.remove('hidden');selectMap(null);try{await loadMapCatalog();renderMapList()}catch(e){$('#mapStatus').textContent=e.message}}
$('#mapBack').onclick=returnLobby;$('#mapNew').onclick=()=>selectMap(null);$('#mapForm').elements.theme.onchange=drawMap;
function paintMap(e){const c=$('#mapCanvas'),r=c.getBoundingClientRect();const x=Math.floor((e.clientX-r.left)/r.width*760/40)*40,y=Math.floor((e.clientY-r.top)/r.height*1450/40)*40;if(x<0||x>720||y<0||y>1400||!mapCellSafe(x,y)){return}const key=x+':'+y,brush=$('#mapBrush').value;mapDraft.cells=mapDraft.cells.filter(cell=>cell.x+':'+cell.y!==key);if(brush!=='erase'){if(mapDraft.cells.length>=300){$('#mapStatus').textContent='Maximal 300 Felder.';return}mapDraft.cells.push({x,y,type:brush})}drawMap();$('#mapStatus').textContent=mapDraft.cells.length+' / 300 Felder'}
$('#mapCanvas').onpointerdown=e=>{e.preventDefault();mapPainting=true;e.currentTarget.setPointerCapture(e.pointerId);paintMap(e)};$('#mapCanvas').onpointermove=e=>{if(mapPainting){e.preventDefault();paintMap(e)}};$('#mapCanvas').onpointerup=$('#mapCanvas').onpointercancel=$('#mapCanvas').onlostpointercapture=()=>{mapPainting=false};
$('#mapForm').onsubmit=async e=>{e.preventDefault();const form=e.target,b=form.querySelector('button[type=submit]');b.disabled=true;try{const body={...Object.fromEntries(new FormData(form)),id:mapDraft.id,cells:mapDraft.cells,published:form.elements.published.checked};const data=await starsRequest('admin/map',body);mapDraft=data.map;mapCatalog=data.maps;renderMapList();$('#mapStatus').textContent='Gespeichert: '+data.map.name}catch(error){$('#mapStatus').textContent=error.message}finally{b.disabled=false}};
$('#mapTest').onclick=async()=>{if(!mapDraft.id){toast('Spielfeld zuerst speichern');return}try{const data=await starsRequest('room/create',{mode:'showdown',fighter:fighterSave.selected,mapId:mapDraft.id,private:true});openRoom(data.room);await startHostedRoom()}catch(e){toast(e.message)}};
const mapChoice=document.createElement('label');mapChoice.textContent='Spielfeld';const mapSelect=document.createElement('select');mapSelect.id='onlineMap';mapChoice.append(mapSelect);$('#onlineMode').parentElement.after(mapChoice);
async function refreshMapChoice(){await loadMapCatalog();mapSelect.replaceChildren();const standard=document.createElement('option');standard.value='';standard.textContent='Standard-Spielfeld';mapSelect.append(standard);for(const map of mapCatalog){const option=document.createElement('option');option.value=map.id;option.textContent=map.name+(map.published?'':' (Entwurf)');mapSelect.append(option)}}
const studioOnlineMenu=showOnlineMenu;showOnlineMenu=async function(mode){await studioOnlineMenu(mode);if(releaseUser)try{await refreshMapChoice()}catch(error){toast('Spielfelder: '+error.message)}};
$('#createOnlineRoom').onclick=async()=>{try{const data=await starsRequest('room/create',{mode:$('#onlineMode').value,private:$('#privateRoom').checked,fighter:fighterSave.selected,mapId:mapSelect.value});openRoom(data.room)}catch(e){toast(e.message)}};

// Fullscreen reveal: one server award, four distinct taps, no reward reroll.
const reveal=document.createElement('section');reveal.className='drop-reveal hidden';reveal.setAttribute('role','dialog');reveal.setAttribute('aria-modal','true');reveal.setAttribute('aria-label','Drop öffnen');reveal.innerHTML='<h1 id="revealTitle">L-DROP</h1><p id="revealRarity" aria-live="polite">SELTEN</p><button id="revealTap" class="drop-tap" aria-label="Drop drehen"><span id="revealCube">★</span></button><p id="revealHint">Tippe viermal auf den Drop</p><div id="revealReward" hidden></div><button id="revealContinue" hidden>WEITER</button>';
document.body.append(reveal);
const revealLevels=['SELTEN','SUPER SELTEN','EPISCH','MYTHISCH','LEGENDÄR'],revealColors=['#63e1a2','#65b9ff','#bc7bff','#ff657e','#ffe16b'];let revealReward=null,revealTaps=0,revealBusy=false,revealRotation=0;
function revealStage(){const target=Math.max(0,revealLevels.indexOf(revealReward.rarity));return Math.min(target,Math.floor(target*revealTaps/4))}
function updateReveal(){const level=revealStage();reveal.style.setProperty('--drop-color',revealColors[level]);$('#revealRarity').textContent=revealLevels[level];$('#revealCube').style.transform='rotateY('+revealRotation+'deg) rotateZ('+((revealTaps%2)*12-6)+'deg)';$('#revealHint').textContent=revealTaps<4?(4-revealTaps)+' Tipps bis zur Belohnung':'GEÖFFNET';$('#revealTap').disabled=revealTaps>=4;if(revealTaps>=4){const reward=$('#revealReward');reward.replaceChildren();const text=document.createElement('p');text.textContent=revealReward.coins+' Münzen · '+revealReward.power+' Powerpunkte · '+revealReward.credits+' Credits · '+revealReward.gems+' Juwelen';reward.append(text);if(revealReward.brawler){const unlocked=document.createElement('h2');unlocked.textContent='NEUER BRAWLER: '+revealReward.brawler;reward.append(unlocked)}reward.hidden=false;$('#revealContinue').hidden=false}}
async function beginDropReveal(type){if(openingDrop||revealBusy)return;if(collection[type]<1){toast('Du hast keinen Drop dieses Typs.');return}openingDrop=true;revealBusy=true;try{const data=await perform('opendrop',{type});if(!data)return;revealReward=data.result;revealTaps=0;revealRotation=0;$('#revealTitle').textContent=type==='mega'?'MEGA-BOX':'L-DROP';$('#revealReward').hidden=true;$('#revealContinue').hidden=true;$('#revealTap').disabled=false;reveal.classList.remove('hidden');document.querySelector('main.lobby').inert=true;releaseNav.inert=true;updateReveal();$('#revealTap').focus()}catch(e){toast(e.message)}finally{openingDrop=false;revealBusy=false}}
$('#revealTap').onclick=()=>{if(revealBusy||!revealReward||revealTaps>=4)return;revealBusy=true;revealTaps++;revealRotation+=180;updateReveal();beep(350+revealTaps*120,.1);setTimeout(()=>{revealBusy=false},320)};
$('#revealContinue').onclick=()=>{if(revealTaps<4)return;reveal.classList.add('hidden');revealReward=null;$('#dropScreen').classList.add('hidden');document.querySelector('main.lobby').inert=false;releaseNav.inert=false;renderMobileShop();updateOrientationGate()};
$('#openDrop').onclick=()=>beginDropReveal(activeDrop);
showDrop=function(type){return beginDropReveal(type)};
$('#mobileOpenL').onclick=()=>beginDropReveal('ldrop');$('#mobileOpenMega').onclick=()=>beginDropReveal('mega');
// Keep gameplay orientation restricted, but allow the reveal overlay to finish safely.
const studioOrientationGate=updateOrientationGate;updateOrientationGate=function(){studioOrientationGate();if(!reveal.classList.contains('hidden')){document.querySelector('main.lobby').inert=true;releaseNav.inert=true}};
window.addEventListener('resize',updateOrientationGate);window.visualViewport?.addEventListener('resize',updateOrientationGate);

// Lessing Coach is the host application; Stars is only its optional subpage.
for(const link of document.querySelectorAll('.release-nav a,.rotate-card a')){link.href='/coach.html';link.textContent='← Lessing Coach';link.onclick=()=>{stopOnline();window.location.assign('/coach.html')}}
versionBadge.textContent='COACH-DESIGN 13';
if($('#starsStartupRetry'))$('#starsStartupRetry').onclick=()=>{document.documentElement.setAttribute('data-stars-loading','true');$('#starsStartupRetry').hidden=true;initializeStars()};
$('#onlineMenu').hidden=true;$('#progressMenu').hidden=true;
function fitCompleteLobby(){
 const viewport=window.visualViewport,w=viewport?.width||window.innerWidth,h=viewport?.height||window.innerHeight;
 const navHeight=(document.body?.classList.contains('courtyard-lobby')||document.body?.classList.contains('in-arena'))?0:releaseNav.getBoundingClientRect().height||48,available=Math.max(1,h-navHeight);
 const root=document.documentElement;root.style.setProperty('--stars-width',w+'px');root.style.setProperty('--stars-height',available+'px');root.style.setProperty('--stars-nav-height',navHeight+'px');root.style.setProperty('--stars-left',(viewport?.offsetLeft||0)+'px');root.style.setProperty('--stars-top',(viewport?.offsetTop||0)+'px');
}
window.addEventListener('resize',fitCompleteLobby);window.addEventListener('orientationchange',fitCompleteLobby);window.visualViewport?.addEventListener('resize',fitCompleteLobby);fitCompleteLobby();

// Courtyard controls follow the illustrated lobby while staying real buttons.
const lobbyIcon=(content)=>'<svg viewBox="0 0 64 64" aria-hidden="true"><g stroke="#07172d" stroke-width="3" stroke-linejoin="round">'+content+'</g></svg>';
const lobbyIcons={
 shop:lobbyIcon('<path d="M13 22h38l5 32H8z" fill="#34d681"/><path d="M21 23v-7a11 11 0 0 1 22 0v7" fill="none" stroke="#ffe589" stroke-width="6"/><path d="M7 21h50v11H7z" fill="#fa586c"/><path d="M20 21h10v11H20zm20 0h10v11H40z" fill="#fff3d2"/><circle cx="32" cy="43" r="8" fill="#ffe068"/>'),
 brawler:lobbyIcon('<path d="m32 3 9 13 16 3-9 14 3 18-19-5-18 5 2-18L7 19l16-3z" fill="#ffe358"/><path d="M19 27c0-15 27-15 27 0v12H19z" fill="#123d6b"/><circle cx="25" cy="29" r="4" fill="#fff4bb"/><circle cx="39" cy="29" r="4" fill="#fff4bb"/><path d="m29 39 3-5 3 5m-8 0v6m10-6v6" fill="none" stroke="#fff4bb"/>'),
 quests:lobbyIcon('<rect x="13" y="10" width="39" height="48" rx="5" fill="#72cbff"/><rect x="23" y="5" width="18" height="12" rx="4" fill="#ffe169"/><path d="m20 29 4 4 8-9m-12 21 4 4 8-9" fill="none" stroke="#134575" stroke-width="5"/><path d="M37 29h9m-9 16h9" stroke="#fff" stroke-width="4"/>'),
 skins:lobbyIcon('<path d="m21 9-16 13 9 13 7-5v27h25V30l7 5 7-13L44 9c-5 12-17 12-23 0z" fill="#d285ff"/><path d="m32 26 4 8 9 2-7 6 1 10-7-5-8 5 2-10-7-6 9-2z" fill="#ffe96d"/>'),
 gift:lobbyIcon('<path d="M9 28h46v29H9z" fill="#239cff"/><path d="M5 20h54v13H5z" fill="#6fcdff"/><path d="M26 20h12v37H26z" fill="#ffdf57"/><path d="M31 21C1 21 11-5 25 9l7 12C61-4 61 23 32 21" fill="#ffd656"/>'),
 crown:lobbyIcon('<path d="m8 17 13 9L32 8l11 18 13-9-6 34H14z" fill="#ffe766"/><path d="M14 46h36v10H14z" fill="#ffa526"/>')
};
for(const [id,icon,label] of [['mobileBrawlers','brawler','BRAWLER'],['mobileShop','shop','SHOP'],['mobileQuests','quests','QUESTS'],['mobileSkins','skins','SKINS']])$('#'+id).innerHTML=lobbyIcons[icon]+'<span>'+label+'</span>';
const lobbyLogo=nativeHome.querySelector('h1');lobbyLogo.innerHTML='<span class="logo-lessing">LESSING</span><span class="logo-stars">STARS</span><span class="logo-star" aria-hidden="true">★</span>';lobbyLogo.setAttribute('aria-label','Lessing Stars');
const profile=document.createElement('div');profile.className='lobby-profile';const avatar=document.createElement('div');avatar.id='lobbyAvatar';avatar.className='lobby-avatar';avatar.setAttribute('aria-hidden','true');const profileText=document.createElement('div');profileText.append($('#mobileAccount'));const profileNote=document.createElement('span');profileNote.id='lobbyProfileNote';profileText.append(profileNote);profile.append(avatar,profileText);nativeHome.querySelector('header').append(profile);
const daily=document.createElement('button');daily.id='lobbyDaily';daily.className='lobby-daily';daily.innerHTML=lobbyIcons.gift+'<span>TÄGLICHE<br>BELOHNUNG<small>ABHOLEN</small></span>';daily.onclick=showProgress;nativeHome.append(daily);
const mode=document.createElement('button');mode.id='lobbyMode';mode.className='lobby-mode';mode.innerHTML='<span class="mode-emblem" aria-hidden="true">✦</span><span><strong>SHOWDOWN</strong><small>Schulhof · Modus wählen</small></span>';mode.onclick=()=>showOnlineMenu('showdown');nativeHome.append(mode);
$('#mobilePlay').innerHTML=lobbyIcons.crown+'<span>SPIELEN</span>';
const courtyardRender=renderMobileHome;renderMobileHome=function(){courtyardRender();const f=fighters.find(f=>f.id===fighterSave.selected)||fighters[0];if(f)setPortrait(avatar,f);profileNote.textContent=releaseAdmin()?'VERWALTUNG':registeredPlayer()?'DEIN KONTO':'ALS GAST SPIELEN';$('#mobilePlay').innerHTML=lobbyIcons.crown+'<span>SPIELEN</span>';};renderMobileHome();
function refreshCourtyardState(){const covered=document.querySelector('.release-screen:not(.hidden),.account-screen:not(.hidden),.brawler-screen:not(.hidden),.game-screen:not(.hidden),.admin-screen:not(.hidden),.hub-view:not(.hidden),#shopScreen:not(.hidden),#accessShield:not(.hidden)');document.body.classList.toggle('courtyard-lobby',!covered);document.body.classList.toggle('in-arena',!$('#gameScreen').classList.contains('hidden'));fitCompleteLobby();resizeOnlineCanvas()}
new MutationObserver(refreshCourtyardState).observe(document.body,{subtree:true,attributes:true,attributeFilter:['class']});refreshCourtyardState();

// AI drafts are previewed locally; publication remains an explicit editor action.
const aiWorkshop=document.createElement('section');aiWorkshop.id='aiWorkshop';aiWorkshop.className='release-screen hidden';aiWorkshop.innerHTML='<header><button id="aiBack">← Verwaltung</button><h1>KI-WERKSTATT</h1></header><div class="release-layout"><section class="release-card"><h2>Deine Idee → spielbarer Entwurf</h2><p>Dieselbe KI-Anbindung wie die Lern-KI. Beschreibe Farben, Fähigkeiten oder das Spielfeld. Der Entwurf wird erst durch Speichern übernommen.</p><form id="starsAIForm"><label>Was möchtest du erstellen?<select id="aiKind"><option value="brawler">Brawler</option><option value="skin">Skin / Outfit</option><option value="map">Spielfeld</option></select></label><label>Beschreibung<textarea id="aiPrompt" minlength="5" maxlength="4000" required placeholder="Ein epischer Eis-Brawler mit blauer Kleidung, Krone und drei eisblauen Projektilen …"></textarea></label><button id="aiGenerate" type="submit">ENTWURF ERSTELLEN</button><p id="aiStatus" role="status" aria-live="polite"></p></form></section><section class="release-card"><h2>Vorschau</h2><canvas id="aiPreview" width="320" height="400" aria-label="KI-Entwurf Vorschau"></canvas><pre id="aiSummary"></pre><button id="aiUse" disabled>IM EDITOR BEARBEITEN</button><p>Figurenbilder werden aus Farben und Accessoires gezeichnet. Du kannst im Brawler-Editor auch eigene Bilder hochladen.</p></section></div>';
document.querySelector('main.lobby').append(aiWorkshop);let aiDraft=null;
function openAIWorkshop(){if(!releaseAdmin()){toast('Nur Admin');return}returnLobby();aiWorkshop.classList.remove('hidden')}
for(const parent of [$('#adminScreen .admin-layout section'),editorScreen.querySelector('header'),mapScreen.querySelector('header')]){const b=document.createElement('button');b.textContent='✦ KI-WERKSTATT';b.className='ai-workshop-button';b.onclick=openAIWorkshop;parent.append(b)}
$('#aiBack').onclick=()=>showAdministration();
function applyDesignPalette(design){for(const [id,key] of [['designOutfit','outfit'],['designHair','hair'],['designSkin','skin'],['designHat','hat']])$('#'+id).value=design[key];drawDesign()}
function draftPreview(){const c=$('#aiPreview'),g=c.getContext('2d');g.clearRect(0,0,320,400);if(aiDraft.kind==='map'){const d=aiDraft.draft;g.fillStyle=d.theme==='forest'?'#214c35':d.theme==='night'?'#162846':'#35556a';g.fillRect(0,0,320,400);for(const cell of d.cells){g.fillStyle={wall:'#be8c54',bush:'#49ae61',lava:'#ff7047'}[cell.type];g.fillRect(cell.x/760*320,cell.y/1450*400,40/760*320,40/1450*400)}$('#aiSummary').textContent=d.name+'\n'+d.cells.length+' Felder · '+d.duration+' Sekunden'}else{applyDesignPalette(aiDraft.draft.design);g.drawImage($('#designCanvas'),0,0);const d=aiDraft.draft;$('#aiSummary').textContent=aiDraft.kind==='skin'?d.name+'\nNeues Outfit':d.name+'\n'+d.rarity+' · '+d.hp+' Leben\n'+d.damage+' Schaden · '+d.projectiles+' Projektile\nSuper: '+d.skill}}
$('#starsAIForm').onsubmit=async e=>{e.preventDefault();const b=$('#aiGenerate');b.disabled=true;$('#aiUse').disabled=true;aiDraft=null;$('#aiStatus').textContent='Die KI erstellt deinen Entwurf …';try{aiDraft=await starsRequest('admin/ai',{kind:$('#aiKind').value,prompt:$('#aiPrompt').value});draftPreview();$('#aiUse').disabled=false;$('#aiStatus').textContent='Entwurf fertig. Noch nicht gespeichert.'}catch(e){$('#aiStatus').textContent=e.message}finally{b.disabled=false}};
const skinStudio=document.createElement('section');skinStudio.id='skinStudio';skinStudio.className='release-screen hidden';skinStudio.innerHTML='<header><button id="skinEditorBack">← Verwaltung</button><h1>SKIN-WERKSTATT</h1></header><div class="release-layout"><section class="release-card"><form id="skinEditorForm"><label>Name<input name="name" maxlength="24" required></label><div class="fields"><label>Outfit<input name="outfit" type="color" value="#2177dc"></label><label>Haare<input name="hair" type="color" value="#593829"></label><label>Haut<input name="skin" type="color" value="#e6a46a"></label><label>Accessoire<select name="hat"><option value="none">Ohne</option><option value="cap">Kappe</option><option value="crown">Krone</option><option value="mask">Maske</option></select></label></div><label>Preis in Juwelen<input name="cost" type="number" min="0" max="1000" value="50" required></label><label class="check"><input name="published" type="checkbox"> Für Spieler freigeben</label><button type="submit">SKIN SPEICHERN</button><p id="skinEditorStatus" role="status"></p></form></section><section class="release-card"><img id="skinEditorPreview" alt="Skin-Vorschau"><p>Ein kosmetisches Outfit verändert keinen Schaden und keine Lebenspunkte.</p></section></div>';
document.querySelector('main.lobby').append(skinStudio);let skinDraftImage='';$('#skinEditorBack').onclick=()=>showAdministration();
$('#aiUse').onclick=async()=>{if(!aiDraft)return;const {kind,draft}=aiDraft;if(kind==='map'){await openMapStudio();selectMap(draft);$('#mapStatus').textContent='KI-Entwurf: prüfen und speichern.'}else if(kind==='brawler'){await showEditor();editorSelect(draft);applyDesignPalette(draft.design);$('#designApply').click();$('#editorForm').elements.published.checked=false}else{returnLobby();skinStudio.classList.remove('hidden');applyDesignPalette(draft.design);skinDraftImage=$('#designCanvas').toDataURL('image/png');$('#skinEditorPreview').src=skinDraftImage;$('#skinEditorForm').elements.name.value=draft.name;for(const key of ['outfit','hair','skin','hat'])$('#skinEditorForm').elements[key].value=draft.design[key];$('#skinEditorForm').elements.published.checked=false;$('#skinEditorStatus').textContent='Noch nicht gespeichert.'}};
$('#skinEditorForm').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{const data=await starsRequest('admin/skin',{...Object.fromEntries(new FormData(e.target)),image:skinDraftImage,published:e.target.elements.published.checked});$('#skinEditorStatus').textContent='Gespeichert: '+data.skin.name;await loadCustomSkins()}catch(e){$('#skinEditorStatus').textContent=e.message}finally{b.disabled=false}};
let customSkinCatalog=[];
async function loadCustomSkins(){const data=await starsRequest('skins');customSkinCatalog=data.skins;for(const skin of data.skins){const im=new Image();im.src=skin.image;customImages.set(skin.id,im)}return data.skins}
const skinsHome=renderMobileHome;renderMobileHome=function(){skinsHome();const skin=customSkinCatalog.find(s=>s.id===viewState.skin);if(skin){$('#mobileFighter').style.backgroundImage='url("'+skin.image+'")';$('#mobileFighter').style.backgroundSize='contain';$('#mobileFighter').style.filter='none'}};
const previousSkins=showSkins;showSkins=async function(){await previousSkins();try{await loadCustomSkins();for(const skin of customSkinCatalog){const row=document.createElement('div');row.className='release-row custom-skin-card';const im=new Image();im.src=skin.image;im.alt=skin.name;const title=document.createElement('strong');title.textContent=skin.name;const b=document.createElement('button');b.textContent=viewState.skin===skin.id?'AUSGEWÄHLT':viewState.skinOwned.includes(skin.id)?'AUSWÄHLEN':'KAUFEN · '+skin.cost+' JUWELEN';b.onclick=async()=>{try{await perform('skin',{id:skin.id});showSkins()}catch(e){toast(e.message)}};row.append(im,title,b);$('#releaseSkinRows').append(row)}}catch(e){toast(e.message)}};
loadCustomSkins().then(()=>renderMobileHome()).catch(()=>{});
versionBadge.textContent='DESIGN 14 · KI-WERKSTATT';
// Illustrated subviews share a compact game navigation.
const gameSideMenu=document.createElement('nav');gameSideMenu.className='game-side-menu';gameSideMenu.setAttribute('aria-label','Spielbereiche');
for(const [label,icon,run] of [['LOBBY','brawler',()=>returnLobby()],['BRAWLER','brawler',()=>$('#mobileBrawlers').click()],['SHOP','shop',()=>openMobileShop()],['SKINS','skins',()=>showSkins()],['QUESTS','quests',()=>showProgress()]]){const b=document.createElement('button');b.innerHTML=lobbyIcons[icon]+'<span>'+label+'</span>';b.onclick=run;gameSideMenu.append(b)}document.querySelector('main.lobby').append(gameSideMenu);
const subviewUpdate=()=>{const covered=document.querySelector('.brawler-screen:not(.hidden),.release-screen:not(.hidden)');document.body.classList.toggle('illustrated-subview',!!covered&&!document.querySelector('#aiWorkshop:not(.hidden),#releaseEditor:not(.hidden),#mapStudio:not(.hidden),#skinStudio:not(.hidden)'));};new MutationObserver(subviewUpdate).observe(document.body,{subtree:true,attributes:true,attributeFilter:['class']});subviewUpdate();
mobileShopScreen.classList.add('illustrated-shop');for(const [i,card] of [...mobileShopScreen.querySelectorAll('.release-card')].entries()){card.classList.add(i?'mega-offer':'drop-offer');const art=document.createElement('div');art.className='offer-art';art.setAttribute('aria-hidden','true');art.innerHTML='<span>L</span>';card.querySelector('h2').after(art);const tiers=document.createElement('div');tiers.className='offer-tiers';for(const [name,color] of [['SELTEN','#65b9ff'],['SUPER SELTEN','#63e1a2'],['EPISCH','#bc7bff'],['MYTHISCH','#ff657e'],['LEGENDÄR','#ffe16b']]){const badge=document.createElement('span');badge.style.setProperty('--tier-color',color);badge.textContent=name;tiers.append(badge)}card.append(tiers)}
const illustratedFighters=renderFighters;renderFighters=function(){illustratedFighters();for(const card of document.querySelectorAll('[data-fighter]')){const f=fighters.find(f=>f.id===card.dataset.fighter);card.style.setProperty('--fighter-color',({STARTER:'#45bced',SELTEN:'#45b868',SUPERSELTEN:'#5c95ec',EPISCH:'#ad65e0',MYTHISCH:'#e2658b',LEGENDÄR:'#e8b640'})[f?.rarity]||'#9264d4')}};
const authArt=document.createElement('div');authArt.className='auth-illustration';authArt.setAttribute('aria-hidden','true');setPortrait(authArt,fighters[0]);$('.account-screen').append(authArt);
$('#mobileSkins').onclick=()=>showSkins();

$('#skinEditorForm').oninput=()=>{const f=$('#skinEditorForm');applyDesignPalette(Object.fromEntries(['outfit','hair','skin','hat'].map(k=>[k,f.elements[k].value])));skinDraftImage=$('#designCanvas').toDataURL('image/png');$('#skinEditorPreview').src=skinDraftImage};
// Online matches use their own input state, independently of the legacy local match.
document.addEventListener('keydown',e=>{if(activeOnlineRoom?.phase!=='playing'||portraitPlayBlocked())return;const keys={ArrowUp:'up',w:'up',ArrowDown:'down',s:'down',ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right',' ':'fire'};const k=keys[e.key]||keys[e.key.toLowerCase()];if(k){e.preventDefault();gameKeys.add(k)}if(e.key.toLowerCase()==='e'){e.preventDefault();networkSuper=true}if(e.key==='Escape')leaveRoom()},true);
window.addEventListener('blur',()=>{networkFire=false;networkSuper=false;stick={dx:0,dy:0};gameKeys.clear()});
const zoomTools=document.createElement('div');zoomTools.className='arena-zoom';zoomTools.innerHTML='<button id="arenaZoomOut" aria-label="Spielfeld verkleinern">−</button><span id="arenaZoomValue">100%</span><button id="arenaZoomIn" aria-label="Spielfeld vergrößern">+</button>';
$('#gameScreen').append(zoomTools);window.arenaZoom=1;for(const [id,step] of [['arenaZoomOut',-.15],['arenaZoomIn',.15]])$('#'+id).onclick=()=>{window.arenaZoom=Math.max(.3,Math.min(1.8,window.arenaZoom+step));$('#arenaZoomValue').textContent=Math.round(window.arenaZoom*100)+'%'};
const superFields=document.createElement('div');superFields.className='fields';superFields.innerHTML='<label>Super-Typ<select name="superType"><option value="burst">Projektile</option><option value="heal">Heilung</option><option value="dash">Sprint</option></select></label><label>Super-Farbe<input name="superColor" type="color" value="#ffdf66"></label><label>Projektilgröße<input name="projectileSize" type="number" min="3" max="20" value="6"></label><label>Projektiltempo<input name="projectileSpeed" type="number" min="200" max="1000" value="650"></label><label>Super-Streuung<input name="superSpread" type="number" step="0.01" min="0" max="1.2" value="0.14"></label>';
$('#editorForm').querySelector('button[type=submit]').before(superFields);const fullEditorSelect=editorSelect;editorSelect=function(f){fullEditorSelect(f);for(const [k,v] of [['superType','burst'],['superColor','#ffdf66'],['projectileSize',6],['projectileSpeed',650],['superSpread',.14]])$('#editorForm').elements[k].value=f?.[k]??v};
const deleteFighter=document.createElement('button');deleteFighter.id='editorDelete';deleteFighter.type='button';deleteFighter.textContent='DIESEN BRAWLER LÖSCHEN';deleteFighter.onclick=async()=>{if(!editorId){toast('Wähle einen gespeicherten Brawler');return}if(!confirm('Brawler löschen? Alle Spieler wechseln bei Bedarf zu Hamza. S.'))return;try{await starsRequest('admin/fighter/delete',{id:editorId});await loadCatalog();renderEditorList();editorSelect(null);toast('Brawler gelöscht')}catch(e){$('#editorStatus').textContent=e.message}};$('#editorForm').append(deleteFighter);
const mapNav=document.createElement('button');mapNav.textContent='SPIELFELDER';mapNav.onclick=()=>openMapStudio();const aiNav=document.createElement('button');aiNav.textContent='✦ KI';aiNav.onclick=()=>openAIWorkshop();releaseNav.append(mapNav,aiNav);const updateEditorNav=()=>{mapNav.hidden=aiNav.hidden=$('#navEditor').hidden};new MutationObserver(updateEditorNav).observe($('#navEditor'),{attributes:true,attributeFilter:['hidden']});updateEditorNav();
const photoDesign=document.createElement('section');photoDesign.className='fighter-designer';photoDesign.innerHTML='<h2>Foto → Brawler mit 3D-Look</h2><p>Oben ein Foto hochladen. Die Bild-KI entfernt den Hintergrund und gestaltet ein transparentes Figurenbild. Benötigt den OpenAI-Bilddienst; erzeugt ein Spielbild, kein drehbares 3D-Modell.</p><label>Outfit / Aussehen<textarea id="photoPrompt" maxlength="3000" placeholder="Blauer Hoodie, futuristische Handschuhe, Eis-Zauber …"></textarea></label><button type="button" id="photoGenerate">FOTO IN BRAWLER VERWANDELN</button><p id="photoStatus" role="status"></p>';
$('#editorForm').append(photoDesign);$('#photoGenerate').onclick=async()=>{const b=$('#photoGenerate');b.disabled=true;$('#photoStatus').textContent='Figurenbild wird erstellt …';try{const data=await starsRequest('admin/image',{image:editorImage,prompt:$('#photoPrompt').value});const im=new Image();im.src=data.image;await im.decode();const c=document.createElement('canvas');c.width=384;c.height=384;c.getContext('2d').drawImage(im,0,0,384,384);editorImage=c.toDataURL('image/webp',.8);if(editorImage.length>220000)throw Error('Bild ist zu groß. Bitte ein einfacheres Design versuchen.');const preview=new Image();preview.src=editorImage;preview.alt='KI-Brawler';$('#editorPreview').replaceChildren(preview);$('#photoStatus').textContent='Fertig. Vorschau prüfen und Brawler speichern.'}catch(e){$('#photoStatus').textContent=e.message}finally{b.disabled=false}};
const shapeFields=document.createElement('div');shapeFields.className='fields';shapeFields.innerHTML='<label>Kopfgröße<input id="designHeadSize" type="range" min="0.75" max="1.35" step="0.05" value="1"></label><label>Körperbreite<input id="designBodyWidth" type="range" min="0.7" max="1.4" step="0.05" value="1"></label><label>Figurengröße<input id="designHeight" type="range" min="0.7" max="1.1" step="0.05" value="1"></label><label>Figur-Basis<select id="designBase"></select></label>';
design.append(shapeFields);for(const f of fighters.slice(0,9)){const o=document.createElement('option');o.value=f.sprite??0;o.textContent=f.name;$('#designBase').append(o)}const basicDrawDesign=drawDesign;
drawDesign=function(){if(!atlasImage.complete||!atlasImage.naturalWidth){basicDrawDesign();return}const c=$('#designCanvas'),g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);const i=Number($('#designBase').value||0),row=Math.floor(i/3),sy=[0,455,875][row],sh=[455,420,379][row],head=Number($('#designHeadSize').value),body=Number($('#designBodyWidth').value),height=Number($('#designHeight').value),w=270,h=370*height,x=(320-w)/2,y=390-h;const buffer=document.createElement('canvas');buffer.width=418;buffer.height=sh;const b=buffer.getContext('2d');b.drawImage(atlasImage,(i%3)*418,sy,418,sh,0,0,418,sh);const pixels=b.getImageData(0,0,418,sh),outfit=$('#designOutfit').value,hair=$('#designHair').value,skin=$('#designSkin').value;const rgb=v=>[1,3,5].map(n=>parseInt(v.slice(n,n+2),16));for(let n=0;n<pixels.data.length;n+=4){const r=pixels.data[n],gg=pixels.data[n+1],blue=pixels.data[n+2],py=Math.floor(n/4/418);if(pixels.data[n+3]<40)continue;let color=null;if(blue>r*1.35&&blue>gg*1.04)color=rgb(outfit);else if(py<sh*.25&&r>gg*1.25&&gg>blue*1.1)color=rgb(hair);else if(py>sh*.25&&py<sh*.53&&r>gg*1.12&&gg>blue*1.12&&r>110)color=rgb(skin);if(color){const light=Math.max(.3,(r+gg+blue)/3/155);for(let k=0;k<3;k++)pixels.data[n+k]=Math.min(255,color[k]*light)}}b.putImageData(pixels,0,0);const split=sh*.47;g.drawImage(buffer,0,split,418,sh-split,160-w*body/2,y+h*.47,w*body,h*.53);g.drawImage(buffer,0,0,418,split,160-w*head/2,y+h*.47-h*.47*head,w*head,h*.47*head);const hat=$('#designHat').value;if(hat!=='none'){g.save();g.translate(160,y+40);g.fillStyle=hat==='crown'?'#ffe15f':hat==='mask'?'#173250':outfit;g.strokeStyle='#091c3a';g.lineWidth=4;if(hat==='crown'){g.beginPath();g.moveTo(-48,12);g.lineTo(-55,-27);g.lineTo(-25,-8);g.lineTo(0,-38);g.lineTo(25,-8);g.lineTo(55,-27);g.lineTo(48,12);g.closePath();g.fill();g.stroke()}else{g.beginPath();g.ellipse(0,hat==='mask'?65:0,56,hat==='mask'?12:17,0,0,Math.PI*2);g.fill();g.stroke()}g.restore()}};
for(const id of ['designHeadSize','designBodyWidth','designHeight','designBase'])$('#'+id).oninput=()=>drawDesign();for(const id of ['designOutfit','designHair','designSkin','designHat'])$('#'+id).oninput=()=>drawDesign();atlasImage.addEventListener('load',()=>drawDesign());drawDesign();versionBadge.textContent='PLAY 15 · SHOWDOWN 10';

$('#revealCube').textContent='L';const styledDrop=showDrop;showDrop=async function(type){reveal.dataset.type=type;await styledDrop(type)};
const starterLobbyRender=renderMobileHome;renderMobileHome=function(){if(releaseReady&&!releaseUser){wallet.coins=500;wallet.power=500;viewState.credits=100}starterLobbyRender()};renderMobileHome();
const designRecord=document.createElement('input');designRecord.type='hidden';designRecord.name='design';$('#editorForm').append(designRecord);$('#editorForm').addEventListener('submit',()=>{designRecord.value=JSON.stringify({outfit:$('#designOutfit').value,hair:$('#designHair').value,skin:$('#designSkin').value,hat:$('#designHat').value,base:Number($('#designBase').value),head:Number($('#designHeadSize').value),body:Number($('#designBodyWidth').value),height:Number($('#designHeight').value)})},true);
const savedDesignSelect=editorSelect;editorSelect=function(f){savedDesignSelect(f);if(f?.design){for(const [id,key] of [['designBase','base'],['designHeadSize','head'],['designBodyWidth','body'],['designHeight','height']])$('#'+id).value=f.design[key]??(key==='base'?0:1);applyDesignPalette(f.design)}};
